### ISSUE TITLE
AHK V2 - Beta 12

### ISSUE THREAD

**Issue by Francois-Bergeron** [tigerlily-dev/tigerlilys-Screen-Dimmer#2]
Hi,

I've been trying to adapt this script to the latest beta version (beta 12), but I'm having a hard time to get the proper `PHYSICAL_MONITOR` from `dxva2\GetPhysicalMonitorsFromHMONITOR`  (the hMonitor value before that is tested and valid). I think the only variance is the `By Ref` removal and `BufferAlloc` to `Buffer`....

Your initial code:
```
GetPhysicalMonitorsFromHMONITOR(hMonitor, PhysicalMonitorArraySize, ByRef PHYSICAL_MONITOR){

   PHYSICAL_MONITOR := BufferAlloc((A_PtrSize + 256) * PhysicalMonitorArraySize)
   if (DllCall("dxva2\GetPhysicalMonitorsFromHMONITOR", "ptr", hMonitor, "uint", PhysicalMonitorArraySize, "ptr", PHYSICAL_MONITOR))
      return NumGet(PHYSICAL_MONITOR, 0, "ptr")
   return false
}
```
My try:
```
GetPhysicalMonitorsFromHMONITOR(hMonitor, PhysicalMonitorArraySize, &PHYSICAL_MONITOR){

   PHYSICAL_MONITOR := Buffer((A_PtrSize + 256) * PhysicalMonitorArraySize)
   if (DllCall("dxva2\GetPhysicalMonitorsFromHMONITOR", "ptr", hMonitor, "uint", PhysicalMonitorArraySize, "ptr", PHYSICAL_MONITOR))
      return NumGet(PHYSICAL_MONITOR, 0, "ptr")
   return false
```

I know this hasn't been maintained in a while, so no worries if you have no plans to maintain this code.
Thanks!

**Comment by 348bestbox** [comment]
Funny that you opened this issue ticket now because last night I decided to try and start porting the Monitor lib used in this app to the latest v2 beta version, so I can build a better UI. I haven't been coding for quite some time. Anyways, ran into the same sort of issue as yourself, I also updated the ByRef and Buffer to the new conventions in the latest beta like you did.

I went a step further removed and just tried to call the DllCall for Setting Brightness (SetMonitorBrightness function), and oddly even though I have the EnumDisplayMonitors function and associated functions working (I can query each monitor for it's name, handle, width, height, etc.), it appears with the new beta conventions I am not calling the basic DllCalls correctly, as they keep returning 0 values (meaning the function failed for some reason). When I look up the Error Code provided, it says

```
ERROR_GRAPHICS_INVALID_PHYSICAL_MONITOR_HANDLE
0xC026258C 
This function failed because an invalid monitor handle was passed to it.
```

However, I've tried passing it directly my monitor handle from passing the variable data in, or just giving it the raw digits (My monitor handles are just simple 5 numbers like 55793, 55979 or something close to that). So my conclusion is that either I'm passing in an invalid monitor handle like the error is returning (which I don't think is the case, but not ruling it out yet), or I'm  not using DllCall correctly, or something entirely different.. but that's as far as I've narrowed this issue down so far. 

I'm pretty strapped for time these days, so who knows when I'll get around to resolving this issue but something I'll work on and update you if I make progress.

**Comment by 348bestbox** [comment]
Disregard my previous comment about DllCalls being incorrect, it's been awhile and I forgot that you have to open and close the Device Context in a certain series of steps in order for these monitor functions to not fail.

Are you receiving an error that looks like this?

```
Error:  Parameter #4 of Monitor.Prototype.GetPhysicalMonitorsFromHMONITOR requires a variable reference, but received an empty string.

	Line#
	351: Throw Error("Unable to get handle to monitor.

Error code: " Format("0x{:X}", A_LastError))
	352: }
	354: {
	356: If (hMonitor := this.GetMonitorHandle(Display))
	356: {
	357: PHYSICAL_MONITOR := ""
	358: PhysicalMonitors := this.GetNumberOfPhysicalMonitorsFromHMONITOR(hMonitor)
--->	359: hPhysicalMonitor := this.GetPhysicalMonitorsFromHMONITOR(hMonitor, PhysicalMonitors, PHYSICAL_MONITOR)
	361: If (SetMethodName = "SetMonitorVCPFeature" || SetMethodName = "SetMonitorColorTemperature")
	361: {
	362: Setting := this.%SetMethodName%(hPhysicalMonitor, Setting, params*)
	363: this.DestroyPhysicalMonitors(PhysicalMonitors, PHYSICAL_MONITOR)
	364: Return Setting
	365: }
	366: Else
```

**Comment by 348bestbox** [comment]
I fixed the issue, but now some more are popping up when running through examples. The main issue I believe is solved though, some variables in the functions that didn't require a preceeding `&` now do. I'll update here with working code once I have successfully tested all examples.

**Comment by 348bestbox** [comment]
@Francois-Bergeron View the updated (updated to be compatible with AHKV2.0-beta.12 Monitor Lib that powers this app here: https://github.com/tigerlily-dev/Monitor-Configuration-Class/blob/master/Monitor%20Class.ahk


This screen dimmer app utilizes a stripped down version of the library shared above, basically stripping out all unnecessary functions/methods. It shouldn't be too hard for you to figure out which code to pull out to put in the screen dimmer. I plan to try and make some progress on the screen dimmer's UI this year so I'll also be updating the code directly at some point between now and end of next year.

**Comment by Francois-Bergeron** [comment]
Ah great timing that we're both looking at this now!
Thanks for your quick update. I'll have a look at your changes tonight or tomorrow, but if you got that working, I should be fine.
